### ISSUE TITLE
IMX347 detected as IMX335

### ISSUE THREAD

**Issue by ch999dev** [OpenIPC/ipctool#28]
board MC-K45 ( SSC30KQ / IMX347 )

https://github.com/OpenIPC/ipctool/blob/792242207cc594ef38b708143cbd32eb84d3bdbe/src/sensors.c#L91
I think something like this would be better
```
int sensor_id = READ(0x57); // 0x3057
switch(sensor_id) {
  case 0x06: // IMX347
  break;
  case 0x07: // IMX335
  break;
}
```

**Comment by widgetii** [comment]
Please fell free to make a PR, don't have IMX347 to test it but can test on IMX335 still
