### ISSUE TITLE
Problem with GK7205V210 chip detection

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/ipctool#73]
```
root@openipc-gk7205v210:~# ipctool
The ipctool installed as remote GitHub plugin
---
chip:
  vendor: Goke
  model: 7205V210
  id: 25e9e400808f41e3
Platform is not supported
root@openipc-gk7205v210:~# 
```

```
root@openipc-gk7205v210:~# ipcinfo -csvtFS
gk7205v210
sc2239
goke
55.53
nor
/usr/bin/majestic
root@openipc-gk7205v210:~#

```

It is possible that the solution can be found here

https://github.com/OpenIPC/ipctool/blob/f17eb6c639428a47bf0f14d54824e1bc932ca0da/src/hal/hisi/hal_hisi.h#L24-L27

**Comment by widgetii** [comment]
Fixed in [3faa063](https://github.com/OpenIPC/ipctool/commit/3faa0632cf5dd48ad9c7b5220aee74471af35c5a)
